// src/styles.ts

export const styles = {
  container: {
    width: '350px',
    fontFamily: 'Arial, sans-serif',
    margin: 0,
    padding: 0,
    backgroundColor: '#2c3e50',
    borderRadius: '10px',
    minHeight: '250px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.2)',
    color: 'white',
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  header: {
    backgroundColor: '#e74c3c',
    color: 'white',
    padding: '15px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopLeftRadius: '10px',
    borderTopRightRadius: '10px',
  },
  headerTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 'bold' as const,
  },
  icon: {
    width: '28px',
    height: '28px',
  },
  closeButton: {
    backgroundColor: 'transparent',
    border: 'none',
    color: 'white',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '5px 10px',
  },
  content: {
    flexGrow: 1,
    padding: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column' as const,
  },
  warningBox: {
    backgroundColor: '#e74c3c',
    color: 'white',
    padding: '20px',
    borderRadius: '8px',
    textAlign: 'center' as const,
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
    width: '100%',
  },
  warningMessage: {
    fontSize: '16px',
    fontWeight: 'bold',
    margin: '0 0 10px 0',
  },
  warningDetails: {
    fontSize: '14px',
    margin: '5px 0',
  },
  noWarning: {
    color: '#ecf0f1',
    fontSize: '18px',
    textAlign: 'center' as const,
  },
  enableSoundButton: {
    marginTop: '10px',
    padding: '8px 12px',
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  footer: {
    backgroundColor: '#34495e',
    color: '#ecf0f1',
    padding: '10px',
    fontSize: '12px',
    textAlign: 'center' as const,
    borderBottomLeftRadius: '10px',
    borderBottomRightRadius: '10px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
  },
};
